---
- name: Ensure systemd service file
  template:
    src: env.j2
    dest: "/etc/restic/env.{{ item.name }}"
    mode: "0600"
  with_items: "{{ restic_backups }}"

- name: Ensure systemd service file
  template:
    src: systemd.service.j2
    dest: "/etc/systemd/system/restic-{{ item.name }}.service"
  with_items: "{{ restic_backups }}"

- name: Ensure systemd timer
  template:
    src: systemd.timer.j2
    dest: "/etc/systemd/system/restic-{{ item.name }}.timer"
  with_items: "{{ restic_backups }}"

- name: systemd daemon-reload
  systemd:
    daemon_reload: true
